### ISSUE TITLE
What is the difference between "abase" and "base"?

### ISSUE THREAD

**Issue by jaysonwillson** [copycat-killer/lain#128]
Hello! I have read their descriptions, and I know meaning of "asynchronous", but do not understand, what does it mean in context of widgets. Could you explain, please? Thank you.

**Comment by aajjbb** [comment]
`base` widget is meant to be customized by the user, you can basically make your custom widget using it, `abase` it's asynchronous sibling. That's it.

**Comment by jaysonwillson** [comment]
Excuse me, but I still do not understand. What does "asynchronous" mean here? What is practical difference between these two widgets for end user?

**Comment by copycat-killer** [comment]
@jaysonwillson `abase` uses [asyncshell](https://github.com/copycat-killer/lain/blob/master/asyncshell.lua) so that commands can be executed in separate processes (i.e. they are not *synchronized* on awesome), while `base` doesn't.

Using `abase` should be a little more cpu demanding, but faster; `base` instead works on awesome stack, so it should be lesser cpu demaning, but may be UI blocking, depending on the use.

That's why internet widgets like `imap`, `mpd` and `weather` use asyncsell too.

**Comment by copycat-killer** [comment]
They're identical in configuration, so whether to use `base` or `abase` depends on the use case.

For instance, if you need network connectivity, which doesn't strictly depend on your machine, then `abase` would be more reactive, while if you just need to check a local resource, then `base` would be lighter.

**Comment by jaysonwillson** [comment]
Now I understand, thank you!
