### ISSUE TITLE
Small (~1 pixel) gaps between windows

### ISSUE THREAD

**Issue by Vivalalinux** [copycat-killer/lain#137]
Hello. I use inverted uselesstile from https://gist.github.com/copycat-killer/c59dc59c9f99d98218eb and I see the following not problem, but a bit annoying thing: in my theme.lua I have:
theme.useless_gap = 0
theme.single_gap = { width = 600, height = 300 }
and when I have >=2 windows in "slave" zone, they have ~1 pixel gaps between them, so that I can see part of background (screenshot: https://i.imgur.com/EVv9os5.png). This does not reproduce with any of standard awesome layouts, and it does also reproduce with other applications like File Managers (size_hints_honor = false in rc.lua). Could you please give an advice, how to fix it? Thank you

**Comment by InfinityTotality** [comment]
This issue is due to the height of your work area not being evenly divisible by the number of clients in the column. I've created a version of the regular uselesstile layout which fixes this by having the bottom window use up all the remaining space in the column the same way all the other lain layouts do. You can get that version here: https://github.com/InfinityTotality/lain/blob/master/layout/uselesstile.lua. If you're feeling adventurous, it should be fairly easy to apply the same changes to the inverted version by comparing the files or reading this commit log: https://github.com/InfinityTotality/lain/commit/c477cc64fd484f9cc1e1c78e9b22e1f099e75838.

**Comment by Vivalalinux** [comment]
Thank you for your reply and wise advice.
It was quite easy to fix inverted uselesstile, because actually the same changes applied to it successfully.

**Comment by InfinityTotality** [comment]
Good to hear! If you used the commit log to make the changes, I actually made a couple more small changes to fix the same issue with multiple slave columns. That commit is here: https://github.com/InfinityTotality/lain/commit/8153bfc1e3cff8a3100ce2e69d444811cd0aef85

**Comment by copycat-killer** [comment]
Can you please post the patch for inverted `uselesstile`, or link an updated gist?

**Comment by Vivalalinux** [comment]
InfinityTotality, yes, I have also applied these changes.

Copycat-killer, here it is. Have been using it for ~4-5 days, everything is just fine. https://gist.github.com/Vivalalinux/71df4b1550dc896f4166

**Comment by InfinityTotality** [comment]
Here's a version with all the spacing intact and also one more change I made (reverted the rounding change on gap calculation size_correction): https://gist.github.com/InfinityTotality/e62013117f7aa96fad48

**Comment by copycat-killer** [comment]
I've updated the original [gist](https://gist.github.com/copycat-killer/c59dc59c9f99d98218eb).

Thank you both. :dancers:
