### ISSUE TITLE
 API key is needed to get access to weather API .

### ISSUE THREAD

**Issue by shmilee** [copycat-killer/lain#146]
widgets/weather doesn't work tody.The reason is the weather API requires a valid APPID for access now.
What the API returns is:
Invalid API key. Please see http://openweathermap.org/faq#error401 for more info.

**Comment by NiclasEriksen** [comment]
So what now? Abandon OMW or apply for an unlimited API-key for lain? I'm sure it would qualify.

**Comment by copycat-killer** [comment]
I contacted OWM because the API key system wasn't working. Now seems fixed, at least with my key.

In ad71a6b I introduced the `APPID` argument. In order to enable the widget again, you just have to freely [register and obtain your key](http://openweathermap.org/appid), and declare it:
```lua
myweather = lain.widgets.weather({
    APPID = "myappid",
    -- [...]
})
```
For the moment, it is mandatory, but I wrote to OWM again to see if they can grant me immunity from usage limit overflow blocking, being this a FOSS project. In that case, `APPID` will become optional/failsafe. I'll post updates here.

In the meantime, let me know if the new argument works.

**Comment by copycat-killer** [comment]
Good news, everyone.

Lain has been added to OpenWeatherMap FOSS project list. This means that, starting from 554d206, the weather widget is enabled again, you don't have to define any new argument. Also, being officially supported, **we no longer have usage limitations**.

A big thank you to OWM team, especially to Ivan and Artem.

Hooray! :dancers:


PS: If you still have some issues, keep posting here. Let me know if all goes well, anyway.
