### ISSUE TITLE
Useless gaps not appearing in some places

### ISSUE THREAD

**Issue by greykiteshield** [copycat-killer/lain#166]
I seem to be getting a bug with the uselesstiles layout. When I use the layout, I seem to be missing gaps on some sides.  I only seem to get the [bottom gaps](https://cloud.githubusercontent.com/assets/5377715/12429860/2b1d5adc-beb2-11e5-9320-845ab54f39ef.png).  When I try to use the resize_gaps on the fly utility it get this [error](https://cloud.githubusercontent.com/assets/5377715/12429903/5dbb79ce-beb2-11e5-8190-48b3111d98cd.png) which says:
```lua
lain/util/init.lua:209: attempt to perform arithetic on a nil value
```
I have changed nothing inside the layout folder and I'm using the zenburn theme.  Let me know what else you need.

**Comment by copycat-killer** [comment]
Did you set your `theme.lua` as [reported in the wiki](https://github.com/copycat-killer/lain/wiki/Layouts#useless-gaps)?

If not, the "bottom gaps" are due to a default Awesome rule. As written in the [main wiki](http://awesome.naquadah.org/wiki/FAQ#How_to_remove_gaps_between_windows.3F), you can remove them adding [this line](https://github.com/copycat-killer/awesome-copycats/blob/master/rc.lua.copland#L647).

**Comment by greykiteshield** [comment]
That line was it.  I had added it but I did it improperly.  My apologies for wasting your time but thank you very much for your help.
