### ISSUE TITLE
pulseaudio widget

### ISSUE THREAD

**Issue by MParolari** [copycat-killer/lain#188]
I'm looking at the pulseaudio widget, and i don't understand a few things:

Without the `pulseaudio.sink` value, how could the user know which sink he's using/monitoring?
And something like `os.execute(string.format("pactl set-sink-volume %d -- +1%%", volumewidget.sink))` that you described in the wiki doesn't work anymore now.

In this moment, `volume_now` isn't a local table, but has a global scope. Why?

If pulseaudio daemon isn't running, the widget isn't very happy and floods me with errors (string matching fails?).  What about check the daemon status? Something like `pulseaudio --check` should work.

Last but not least: how can you be sure that your default command detects the default sink?
Default sink and its volume (_without_ left-right balance) can be retrieved from `pacmd dump` (and some pattern matching) without the problem of localized output.

**Comment by copycat-killer** [comment]
> Without the `pulseaudio.sink` value, how could the user know which sink he's using/monitoring?

In `pacmd list-sinks`, the current sink index is indicated with an asterisk, and this is used in `pulseaudio.cmd` as a wildcard. The user doesn't need to define which sink is being used. But you can redefine `args.cmd` with the correct command if it doesn't work.

> And something like `os.execute(string.format("pactl set-sink-volume %d -- +1%%", volumewidget.sink))` that you described in the wiki doesn't work anymore now.

I removed the "--". But keep in mind that is just an example. The lua code will be always correct, but the commands themselves may be very machine-dependent.

> In this moment, `volume_now` isn't a local table, but has a global scope. Why?

Because otherwise you wouldn't be able to use it in `rc.lua`. This is the same logic every other widgets have.

> What about check the daemon status?

The widgets are meant to be simple.

Why `pulseaudio` daemon should not be active if you're planning to use this widget?

If you give me a good reason or use case, I'll consider doing the check first.

> Last but not least: how can you be sure that your default command detects the default sink?

I am not. Infact, that's why you have the ability to define `args.cmd`, as I wrote above.

Involving `pacmd dump` still requires another call to `pactl` in order to grab the infos. The asterisk wildcard trick is quick and easy and works so far. At least, still nobody complains about that.

**Comment by MParolari** [comment]
> In pacmd list-sinks, the current sink index is indicated with an asterisk

I didn't know this, sorry; now the sed command makes sense.

> Why pulseaudio daemon should not be active if you're planning to use this widget?

If something goes wrong, or pulseaudio is crashing, or the user kills it, or it's started after awesome-wm from some script or application, ....
Murphy's law docet.

Anyway, thanks for the reply, I figured out how the widget works.

**Comment by copycat-killer** [comment]
Murphy's law is neither a valid reason nor a use case. Anything can go wrong.

If `pulseaudio` crashes, is killed or is not started, then is reasonable that the widget gives errors as well.
