### ISSUE TITLE
Net widget picks up the first configured device

### ISSUE THREAD

**Issue by Unode** [copycat-killer/lain#191]
Hi Luke,

I started using docker on my machine and the net widget was no longer displaying any activity even when I was sure I was transferring something.

After inspecting the code I realized that if no interface is specified the widget picks up the first one "UP" where "first" means alphabetical order.
Before installing docker this worked fine as either the ethernet or wifi interfaces were picked up, however after installing docker, `docker0` is always the first interface to match. Since I'm not doing any transference inside docker the counters are at zero most of the time.

On the other hand, on the laptop I often toggle between cable and wifi as I move around and sometimes both are "UP" simultaneously.
Setting up a fixed interface on the configuration doesn't work that well on this scenario so either I have one widget per interface or I won't get the right reading.

So after all this I started to wonder if it would be possible to add up the transference rates of all the interfaces that are "UP". Optionally limiting to a few interfaces by passing a table or iterator via `args.iface`.
The current "string" interface would still be kept for backwards compatibility.

Would you be ok with this functionality?

**Comment by copycat-killer** [comment]
Notice that `net.get_device` can be replaced by a function in `args.iface`. But if you're considering to enhance the widget by automatically detecting an often changing `iface`, then go on.

You could extend `net.get_device` by passing it an argument, i.e. "static"/"dynamic". If "static", it'll work like usual, otherwise, it'll do your new functionality.
