### ISSUE TITLE
Magnify_client doesn't respond to incmwfact

### ISSUE THREAD

**Issue by teranex** [copycat-killer/lain#195]
When a client is set to magnify using `lain.util.magnify_client` it's size doesn't grow or shrink as does a client in the default magnify layout, when using `modkey+h` and `modkey+l`. However when disabling magnify and reenabling it again the size of the client is different. It would be very useful if you could actually see it grow/shrink.

**Comment by copycat-killer** [comment]
The function `magnify_client` sets the client to float and resizes it.

When you later call `awful.client.incwfact`, this one only works on non-floating clients, that's why you don't see the lain-magnified client changing its geometry.

Plus, `magnify_client` calls `awful.tag.getmwfact`, and that's why toggling it you see the geometry finally changing.

In order to enable `magnify_client` to behave like `magnifier`, update to latest commit and use `lain.util.mc()` after `incmwfact`:

```lua
awful.key({ modkey,           }, "l",
function ()
    awful.tag.incmwfact( 0.05)
    lain.util.mc()
end),

awful.key({ modkey,           }, "h",
function ()
    awful.tag.incmwfact(-0.05)
    lain.util.mc()
end),
```

**Comment by teranex** [comment]
This works indeed. Thanks!
