### ISSUE TITLE
Error in bat.lua when battery is 100% but still on A/C

### ISSUE THREAD

**Issue by Foxtrot** [copycat-killer/lain#209]
Seems when the battery is on 100% and still plugged in it does not change to say "A/C", but if I restart awesomewm it will say "A/C", but error out every time the applet is updated with "bat.lua:148: attempt to compare string with number"

**Comment by Foxtrot** [comment]
I should mention I am using the latest lain from the AUR package.

**Comment by copycat-killer** [comment]
Assuming this happens when you wait widget timeout (30s default) and then you restart wm, I can't manage to replicate the issue.

If your widget is able to execute until that line, it means that `bat_now.status == "Discharging"` is true, and it shouldn't. A problem with buffers/ram?

Let's add a type checking. Try latest commit.

**Comment by Foxtrot** [comment]
Works great with latest commit!
Thank you very much.
