### ISSUE TITLE
termite terminal not working with quake

### ISSUE THREAD

**Issue by sboysel** [copycat-killer/lain#211]
Using lain at 41ccab3196c0051d7ce68e1e77ca97acf20db52d with my fork of awesome-copycats and it seems that of the terminals I have installed, `xterm` toggles with `Mod + z` but `termite` does not.  No errors, it just simply does not appear.  My fork, https://github.com/sboysel/awesome-copycats/commit/67632cc13842af1beaf20c0126f0156bb905b83c, has [some very minor differences](https://github.com/copycat-killer/awesome-copycats/compare/master...sboysel:master) from copycat-killer/awesome-copycats@0d80ca01235a29e4fca1237225fc11b438a01045 that I don't *think* are related to this issue.

    [sam@archbook ~ 08:22:18]$ uname -a
    Linux archbook 4.6.3-1-ARCH #1 SMP PREEMPT Fri Jun 24 21:19:13 CEST 2016 x86_64 GNU/Linux
    [sam@archbook ~ 08:22:13]$ termite --version
    termite v11

Let me know if I should open the issue in awesome-copycats or if the issue is beyond the scope of what you're willing to support.

**Comment by copycat-killer** [comment]
This is the right scope.

GTK based applications have `--name` option for setting windows name.

Quake has `-name` as default (only one dash) since it was originally planned for X terminals.

All you have to do is to set `argname` properly:

```lua
-- quake terminal
local quakeconsole = {}
for s = 1, screen.count() do
   quakeconsole[s] = lain.util.quake({ app = "termite", argname = "--name %s" })
end
```

Read [here](https://github.com/copycat-killer/lain/wiki/Utilities#quake) if you wish to customize other parameters.

**Comment by sboysel** [comment]
Thank you!
