### ISSUE TITLE
lain in LuaRocks

### ISSUE THREAD

**Issue by aajjbb** [copycat-killer/lain#231]
Hi,

There's a recent discussion in awesome [repo](https://github.com/awesomeWM/awesome/issues/1171) about hosting awesome's extensions in some form of centralized package manager and LuaRocks is being considered.

As lain is one of the most successful lain extensions, what do you think about uploading lain there ?

**Comment by copycat-killer** [comment]
I read some mixed feelings about that in the linked discussion.

Personally, I don't think it would be necessary to have a plugin manager, especially when we have a thorough wiki, and using git is very easy both to download and keep sources up to date.

On the other way, spreading visibility is always good.

If you're willing to create and maintain a LuaRock package, I'd be glad to let you do so. Otherwise I may do it myself, but with longer times.

> lain is one of the most successful lain extensions

![inception](https://linx.li/a4lt6bt0.jpg "-_-")

**Comment by copycat-killer** [comment]
I read some mixed feelings about that in the linked discussion.

Personally, I don't think it would be necessary to have a plugin manager, especially when we have a thorough wiki, and using git is very easy both to download and keep sources up to date.

On the other way, spreading visibility is always good.

If you're willing to create and maintain a LuaRock package, I'd be glad to let you do so. Otherwise I may do it myself, but with longer times.

> lain is one of the most successful lain extensions

![inception](https://linx.li/selif/a4lt6bt0.jpg "-_-")

**Comment by airtonix** [comment]
It's super trivial to automate this with github actions.
