### ISSUE TITLE
Problem with abase output.

### ISSUE THREAD

**Issue by geripgeri** [copycat-killer/lain#312]
* output of `awesome -v` and `lua -v`
```
awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.1
```
* Expected behavior:
```
20:38
```
* Actual behavior:

```
nothing
```

* steps to reproduce the problem

Before version 4.0 the command  `"TZ=Europe/London date +'%R'"` returns with correct data, after 4.0 there is no return. This also happens to other complex commands.

**I also reported an issue to https://github.com/awesomeWM/awesome/issues/1532, please have a look.**

Example code: 

```
local clock = lain.widgets.abase({
    timeout = 10,
    cmd = "TZ=Europe/London date +'%R'",
    settings = function()
        widget:set_markup(output)
    end
})
```

**Comment by copycat-killer** [comment]
As others already told you, you need to use a table.

```lua
local mytextclock = lain.widgets.abase({
    timeout = 60,
    cmd = { awful.util.shell, "-c", "TZ=Europe/London date +'%R'" }
})
```

Note that, since `wibox.widget.textclock` uses `Glib.DateTime`, [you can include time zone offset](https://developer.gnome.org/glibmm/stable/classGlib_1_1DateTime.html#a820ed73fbf469a24f86f417540873339) in it with "%z" or "%Z".

@psychon I just want to tell you that `abase` (which I'll rename to `watch` to be more coherent\*) does exactly what `awful.widget.watch` does. The only difference, as [stated in the wiki](https://github.com/copycat-killer/lain/wiki/abase#description), is that your watcher only returns the widget, while it would  be useful to be able to control its update function and timer.

\* Previously there was also a `base` widget, synchronous, whereas `abase` is... you can guess. I removed `base` because of @Elv13's holy war against `io.popen`.

I'll do the rename, clarify this point in my wiki. 

I opened a PR to highlight the question: https://github.com/awesomeWM/awesome/pull/1540

If merged, I'll remove this widget and leave it all to you.
