### ISSUE TITLE
lain/widget/alsabar.lua:84: attempt to call method 'set_value' (a nil value) when using `vertical = true`

### ISSUE THREAD

**Issue by tomoyat1** [copycat-killer/lain#315]
## output of `awesome -v` and `lua -v`
`awesome -v`
```
awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.0
```

`lua -v`
```
Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio
```
## expected behavior and actual behavior
* Expected Behaviour: alsabar and pulsebar gets shown in vertical orientation properly
* Actual behaviour: Fails with error
```
2017-02-14 09:45:29 E: Error during a protected call: ...ome/tomoyat1/.config/awesome/lain/widget/alsabar.lua:84:
 attempt to call method 'set_value' (a nil value)
```
## Steps to reproduce problem
1. Enable `vertical = true` in options for alsabar/wibar

**Comment by copycat-killer** [comment]
Removed those options in order to make the user manipulate the `progressbar` as he wants.

If you want a vertical bar, just add `wibox.container.rotate(volume.bar, "east")` instead of `volume.bar` in your wibar. Be sure to set `{alsa,pulse}bar` input height argument to your wibar height at most, otherwise the bar will not be shown.
