### ISSUE TITLE
Using conky with the quake utility

### ISSUE THREAD

**Issue by ravila4** [copycat-killer/lain#326]
Hi, I've been trying unsuccessfully to set conky as my quake application.
Is there a way to do this? I tried setting the arg_name parameter to both "-name %s" and "--name %s", neither of them work.
Any help is appreciated.

**Comment by copycat-killer** [comment]
You don't need `quake` for this. Just start `conky -d` and use the following keybinding:

```lua
    awful.key({ modkey }, "c", -- customize your keys here
    function()
        for _,c in ipairs(client.get()) do
            local classname = c.class:lower() .. " " c.name:lower()
            if classname:match("conky") then
               c.minimized = not c.minimized
               c.ontop = not c.minimized
               c:move_to_tag(awful.screen.focused().selected_tag)
           end
        end
    end),
```

---

Just FYI, in order to spawn `conky` with `quake`, you have to pass it as a terminal-emulator application argument. For instance:

```lua
function theme.at_screen_connect(s)
    -- Quake application
    s.quake = lain.util.quake({ app = "urxvt", extra = "-e conky" })
    -- [...]
```

but this would require an investigation on how to pass more arguments to `extra` in order to make `conky` output to console.

**Comment by ravila4** [comment]
Thank you! This solved my problem.
