### ISSUE TITLE
Why is the widget a global and not passed to the settings function as settings(widget)

### ISSUE THREAD

**Issue by axujen** [copycat-killer/lain#336]
Question in the title, why is the [widget](https://github.com/copycat-killer/lain/blob/586c54a25750fd90d91c15ac8eb818b2613de582/widget/mpd.lua#L97) object passed as a global instead of being passed as an argument to the settings function?

The fact that widget is a global means it can be updated by other widgets and this causes some really funny behavior like:
![this](https://s2.postimg.org/jphzmg1kp/Screenshot-1491089244.png)
Left my mpd widget, right the mpd widget from the dremora theme (didnt know it actually defined one) updating my battery widget.

Simple fix, pass widget as an argument to the settings() function, you can even keep it as a global aswell to for backwards compatibility with old configs.

**Comment by copycat-killer** [comment]
> Question in the title, why is the widget object passed as a global instead of being passed as an argument to the settings function?

The behaviour is actually different: that line adds a new pointer in the scope of `settings` which enables the user to use the inner widget via `widget` variable.

The global issue you are referring to is due to the table widget instantiated outside the factory function. This is a sort of a "legacy" template inherited from `vain`, which was legitimated until now by the fact that `mpd` (like other widgets) is meant to be instantiated at most once.

Defining the widget table in the factory function solves it without having to deal with API compatibility.

I'll counter push a fix to this and other affected widget as well.
