### ISSUE TITLE
quake.lua:165: attempt to index a nil value

### ISSUE THREAD

**Issue by elw00d** [copycat-killer/lain#358]
Hello ! I've experienced with issue when migrated from Ubuntu 14.04 with awesomewm 4.0 to 16.04 and 4.2 respectively.

```
2017-08-23 12:05:51 W: awesome: luaA_dofunction:77: error while running function!
stack traceback:
	/home/elwood/.config/awesome/lain/util/quake.lua:165: in function 'toggle'
	/home/elwood/.config/awesome/rc.lua:364: in function 'press'
	/usr/local/share/awesome/lib/awful/key.lua:91: in function </usr/local/share/awesome/lib/awful/key.lua:91>
error: /home/elwood/.config/awesome/lain/util/quake.lua:165: attempt to index a nil value
```

My configuration

```
s.quake = lain.util.quake({ 
        app = 'gnome-terminal',
        extra = "--disable-factory --profile=Quake",  -- Fixes gnome-terminal's unwanted existing windows reusing behavior
        argname = "--name %s",
        height = 0.653, -- To exactly match with gnome-terminal 'resolution' in laptop mode
        border = 3,
	followtag = true
    })
```

awesome v4.2 (Human after all)
 • Compiled against Lua 5.2.4 (running with Lua 5.2)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.4
 • LGI version: 0.9.0

**Comment by copycat-killer** [comment]
[They removed `disable-factory`](https://patchwork.openembedded.org/patch/126517), so it's not possible anymore to have a single `gnome-terminal` to spawn and use with `quake`.

In order to make it work again, the logic should focus on PIDs instead of window clients, but that would require to avoid Awesome API and go down to the OS level, which frankly is a bad workflow.

Terminals like `gnome-terminal` and `konsole` are too dependent on the DE they belong to, therefore it's improbable that they can adapt to anything different.

But the good news is: you really don't need them. There's plenty of much better and faster terminals, even VTE-based. I suggest `termite`, otherwise pick one from [here](https://wiki.archlinux.org/index.php/List_of_applications#Terminal_emulators), besides the above cited, of course, and `yakuake` or `guake`, [which constrast in behaviour with `quake`](https://github.com/copycat-killer/lain/issues/219#issuecomment-237487373).

I will update the wiki.
