### ISSUE TITLE
mpd widget keeps creating files in /tmp folder

### ISSUE THREAD

**Issue by gokcehan** [copycat-killer/lain#98]
I have a pretty basic mpd widget setup (except that I'm using [mopidy](https://www.mopidy.com/) instead of mpd) and I realized some files are constantly created every 2 seconds in `/tmp/asyncshell` with a content:

    OK MPD 0.17.0
    ACK [2@0] {password} wrong number of arguments for "password"
    volume: 100
    repeat: 0
    random: 0
    single: 0
    consume: 0
    playlist: 0
    playlistlength: 0
    xfade: 0
    state: stop
    OK
    OK
    OK

When I delete the folder `/tmp/asyncshell` I start to get the following error every 2 seconds:

    Oops, an error happened!
    /usr/share/awesome/lib/lain/widgets/mpd.lua:67: attempt to index local 'f' (a nil value)

Is this bug related to lain?

**Comment by copycat-killer** [comment]
That's how `asyncshell` works, of course if you delete its files there would be nil pointers!

Why do you feel the need to delete temporary files in the system temporary folder?

`/tmp` is cleared at boot or cyclically from the OS.

Your problem is the **500 b** file every 2 second? That's approximately 100mb in 100 hours!

Jeez.
